# This is a basic workflow to help you get started with Actions

name: OpenPL Builder

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop, main, master ]
  pull_request:
    branches: [ develop, main, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_mac:
    # The type of runner that the job will run on
    runs-on: macos-latest
    if: "contains(github.event.head_commit.message, '[B]')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Run Setup
        run: ./OpenPL/Setup.sh
 
      - name: Build with xcodebuild
        run: xcodebuild -project OpenPL/Builds/MacOSX/OpenPL.xcodeproj
        
      - name: Download zip
        run: brew install zip
        
      - name: Zip build
        run: zip -j OpenPL/Builds/MacOSX/build/Debug/OpenPL.zip OpenPL/Builds/MacOSX/build/Debug/OpenPL.dylib
        
      - name: Upload Mac Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          # Artifact name
          name: OpenPL.dylib
          # A file, directory or wildcard pattern that describes what to upload
          path: OpenPL/Builds/MacOSX/build/Debug/OpenPL.zip
        
  build_linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest        
    if: "contains(github.event.head_commit.message, '[B]')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Run Setup
        run: ./OpenPL/Setup.sh
 
      - name: Build with make
        run: make -C OpenPL/Builds/LinuxMakefile/
        
      - name: Zip build
        run: zip -j OpenPL/Builds/LinuxMakefile/build/OpenPL.zip OpenPL/Builds/LinuxMakefile/build/libOpenPL.so
        
      - name: Upload Linux Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          # Artifact name
          name: OpenPL.so
          # A file, directory or wildcard pattern that describes what to upload
          path: OpenPL/Builds/LinuxMakefile/build/OpenPL.zip
        
  build_windows:
    runs-on: windows-latest
    if: "contains(github.event.head_commit.message, '[B]')"
    
        # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Cache the vcpkg folder as it compiles all code from scratch everytime
      - name: Cache vcpkg
        uses: actions/cache@v2.1.4
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: OpenPL/External/vcpkg
          # Redo the cahce everytime we change the Setup.bat files
          key: ${{ hashFiles('OpenPL/Setup.bat') }}
      
      - name: Run Setup
        run: ./OpenPL/Setup.bat
        
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
 
      - name: Build with visual studio build
        run: msbuild OpenPL/Builds/VisualStudio2019/OpenPL.sln
        
      - name: Zip build
        run: 7z a 'OpenPL\Builds\VisualStudio2019\x64\Release\Dynamic Library\OpenPL.7z' 'OpenPL\Builds\VisualStudio2019\x64\Release\Dynamic Library\OpenPL.dll'
        
      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          # Artifact name
          name: OpenPL.dll
          # A file, directory or wildcard pattern that describes what to upload
          path: 'OpenPL\Builds\VisualStudio2019\x64\Release\Dynamic Library\OpenPL.7z'
